### ISSUE TITLE
Missing Source for Submodule "PanoSpaceDreamer"

### ISSUE THREAD

**Issue by LonelVino** [liwrui/SceneDreamer360#2]
Hi, this is a pretty nice job!

But what is the source of the submodule "PanoSpaceDreamer"? I am unable to proceed because:
1. There is no .gitmodules file in the repository which would normally contain the URL and path of the submodule.
 2. A search for "PanoSpaceDreamer" on GitHub and other repositories has not yielded any results.

Thank you for your assistance.

**Comment by liwrui** [comment]
Hi,

Thank you for bringing this to our attention and for the positive feedback!

We’ve addressed the issue regarding the "PanoSpaceDreamer" submodule. The code has been updated, and we’ve included the necessary information for the submodule. Please take a look and let us know if everything is now working on your end.

Thanks again for your assistance, and feel free to reach out if you have any further questions!

Best regards,
Wenrui

**Comment by LonelVino** [comment]
Thanks for your prompt response!

Best regards

**Comment by lll-gen** [comment]
Has anyone successfully run the test? I'm seeing a missing data issue on my end.    ”assert self.num_samples >= 1 or self.total_size == 0“
